sudo: required
services:
  - docker

before_install:
  - docker build -t ranjish83/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ranjish83/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-615817760910"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
